# Generated by Django 3.1.5 on 2021-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210204_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, max_length=240),
        ),
    ]
